
package gui;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author NagyDominik(Szf_N_20
 */
public class kopapirollo extends javax.swing.JFrame {


    public kopapirollo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Ko = new javax.swing.JButton();
        Papir = new javax.swing.JButton();
        Ollo = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Ko.setText("jButton1");

        Papir.setText("jButton2");

        Ollo.setText("jButton3");

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ko)
                    .addComponent(Papir)
                    .addComponent(Ollo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Ko)
                        .addGap(18, 18, 18)
                        .addComponent(Papir)
                        .addGap(28, 28, 28)
                        .addComponent(Ollo)))
                .addGap(45, 45, 45)
                .addComponent(jToggleButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Válassz! (kő/papír/olló) (Kérlek használj kis betüket)");
        String jatekos = scanner.nextLine();
      

        Random random = new Random();
        int randomSzam = random.nextInt(3);
        
        String gepValaszt;
        if (randomSzam == 0) {
            gepValaszt = "Kő";
        } else if (randomSzam == 1) {
            gepValaszt = "Papír";
        } else {
            gepValaszt = "Olló";
        }
        System.out.println("A gép választása: " + gepValaszt + "!");
        
        if (jatekos.equals("kő")) {
            if (gepValaszt.equals("Papír")) {
                System.out.println("A gép nyert!");
            } else if (gepValaszt.equals("Olló")) {
                System.out.println("Te nyertél!");
            } else {
                System.out.println("Döntetlen!");
            }
        } else if (jatekos.equals("papír")) {
            if (gepValaszt.equals("Olló")) {
                System.out.println("A gép nyert!");
            } else if (gepValaszt.equals("Kő")) {
                System.out.println("Te nyertél!");
            } else {
                System.out.println("Döntetlen!");
            }
        } else if (jatekos.equals("olló")) {
            if (gepValaszt.equals("Kő")) {
                System.out.println("A gép nyert!");
            } else if (gepValaszt.equals("Papír")) {
                System.out.println("Te nyertél!");
            } else {
                System.out.println("Döntetlen!");
            }
        } else {
            System.out.println("Érvénytelen választás!");
        }
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ko;
    private javax.swing.JButton Ollo;
    private javax.swing.JButton Papir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
